name: Publish Solidity Package

on:
  push:
    branches:
      - master
      - solc-0.6
      - solc-0.7

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Publish Solidity Package
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # install dependencies
          yarn
          # compile
          yarn run generate-bytecode
          cd contracts
          # publish prepare
          yarn run prepare
          # Will be published when the package.json file is modified
          version=$(yarn versions --json | jq -er '.data."@acala-network/contracts"')
          # publish
          yarn publish --version=$version --access=public
